# Generated by Django 2.2.5 on 2019-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='vistas',
            field=models.IntegerField(blank=True, default=0, verbose_name='vistas'),
            preserve_default=False,
        ),
    ]
