# Generated by Django 2.2.5 on 2019-10-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro_vistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigoAdmin',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Usuario')),
            ],
        ),
    ]
