# Generated by Django 2.2.5 on 2019-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(blank=True, max_length=1, verbose_name='Status'),
        ),
    ]
