# Generated by Django 2.2.5 on 2019-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_codigoadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoadmin',
            name='codigo',
            field=models.CharField(max_length=6, verbose_name='codigo'),
        ),
    ]
