# Generated by Django 2.2.5 on 2019-10-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20191025_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='costo',
            field=models.IntegerField(default=0, verbose_name='costo'),
        ),
        migrations.AddField(
            model_name='revista',
            name='costo',
            field=models.IntegerField(default=0, verbose_name='costo'),
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=15, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=15, verbose_name='apellido_materno')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('saldo', models.IntegerField(default=0, verbose_name='saldo')),
                ('favoritos', models.ManyToManyField(blank=True, to='biblioteca.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.login')),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200, verbose_name='texto')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.login')),
            ],
        ),
    ]
