# Generated by Django 2.2.5 on 2019-10-28 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_comprar'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='login',
            name='fecha_modificacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(blank=True, default='B', max_length=1, verbose_name='status'),
        ),
    ]
