# Generated by Django 2.2.5 on 2019-10-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20191028_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.CharField(default='o', max_length=500, verbose_name='sinopsis'),
        ),
    ]
