# Generated by Django 2.2.5 on 2019-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_auto_20191029_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=1000, verbose_name='texto'),
        ),
    ]
