# Generated by Django 2.2.5 on 2019-10-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_auto_20191029_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='favoritos',
        ),
    ]
